# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f3e5ffb3b63573af30d1e83406a3216a4372a9913996368c3447fce660c6bf478652f3bae03d7069f3de76d7281db218d99e407db0039b25f30101d9097f566

test:
  secret_key_base: 7cb6b28a698e8e96bcfe6fde150a670f95f7d95fd961aaa753089523604c21c6cac0802c978d4c0f17574d5d0726ee38749229061b6de45bf2d3757f30a1aaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
